apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: crizmas
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000